nginx:
  build: ./nginxplus
  container_name: nginx
  links:
  - consul
  ports:
  - "80:80"
  - "8080:8080"

consul:
  command: -server -bootstrap -advertise 10.0.2.15
  image: progrium/consul:latest
  container_name: consul
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

registrator:
  command: consul://consul:8500
  image: gliderlabs/registrator:latest
  container_name: registrator
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"

service1:
  image: tutum/hello-world:latest
  container_name: service1
  environment:
    SERVICE_80_NAME: http
    SERVICE_NAME: service1
    SERVICE_TAGS: production
  ports:
  - "8081:80"

service2:
  image: google/golang-hello:latest
  container_name: service2
  environment:
    SERVICE_80_NAME: http
    SERVICE_NAME: service2
    SERVICE_TAGS: production
  ports:
  - "8082:8080"
