- hosts: all
  sudo: true
  tasks:

    - name: Setup Autoscaling Demo | Install curl from apt
      apt: update_cache=yes pkg=curl

    - name: Setup Autoscaling Demo | Install git from apt
      apt: update_cache=yes pkg=git

    - name: Setup Autoscaling Demo | Install siege from apt
      apt: update_cache=yes pkg=siege

    - name: Setup Autoscaling Demo | Install docker.io from apt
      shell: curl -sSL https://get.docker.com/ | sh      

    - name: NGINX Plus | Copying NGINX Plus repository certificate
      copy: src=files/nginx-repo.crt dest=/srv/NGINX-Demos/autoscaling-demo/docker_base/nginx-repo.crt

    - name: NGINX Plus | Copying NGINX Plus repository key
      copy: src=files/nginx-repo.key dest=/srv/NGINX-Demos/autoscaling-demo/docker_base/nginx-repo.key

    - name: Setup Autoscaling Demo | Create docker base image
      shell: /usr/bin/docker build -t nginxplus .
      args:
        chdir: /srv/NGINX-Demos/autoscaling-demo/docker_base

    - name: Setup Autoscaling Demo | Create docker lb image
      shell: /usr/bin/docker build -t nginxpluslb .
      args:
        chdir: /srv/NGINX-Demos/autoscaling-demo/docker_lb

    - name: Setup Autoscaling Demo | Create docker ws image
      command: /usr/bin/docker build -t nginxplusws .
      args:
        chdir: /srv/NGINX-Demos/autoscaling-demo/docker_ws

    - name: Setup Autoscaling Demo | Get Elasticsearch docker image
      command: /usr/bin/docker pull elasticsearch
