- hosts: all
  sudo: true
  tasks:

    - name: Setup Consul Demo | Install curl from apt
      apt: update_cache=yes pkg=curl

    - name: Setup Consul Demo | Install git from apt
      apt: update_cache=yes pkg=git

    - name: Setup Consul Demo | Install jq from apt
      apt: update_cache=yes pkg=jq

    - name: Setup Consul Demo | Install docker.io from apt
      shell: curl -sSL https://get.docker.com/ | sh      

    - name: Setup Consul Demo | Install docker-compose
      shell: curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

    - name: Setup Consul Demo | Apply executable permissions to the docker-compose binary
      shell: chmod +x /usr/local/bin/docker-compose

    - name: NGINX Plus | Copying NGINX Plus repository certificate
      copy: src=files/nginx-repo.crt dest=/vagrant/nginxplus/nginx-repo.crt

    - name: NGINX Plus | Copying NGINX Plus repository key
      copy: src=files/nginx-repo.key dest=/vagrant/nginxplus/nginx-repo.key

    - name: Setup Consul Demo | Build the container images and spin them up (Please have some patience, this step is going to take a while)
      shell: /usr/local/bin/docker-compose up -d
      args:
        chdir: /vagrant/
     
