---
- hosts: localhost
  become: true
  roles:
    - role: nginxinc.nginx
      vars:
        type: plus
        license:
          certificate: ~/.ssh/ngx-certs/nginx-repo.crt
          key: ~/.ssh/ngx-certs/nginx-repo.key
